[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sigireddy viswesh", email = "98519767+Viswesh934@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "uvicorn>=0.53.0",
]

[project.scripts]
api = "api:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
